apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      name: deamonset-example
  template:
    metadata:
      labels:
        name: deamonset-example
    spec:
      nodeSelector:
        apptype: xavier-app #这里的xavier-app是apptype的值，也就是label
      containers:  
      - name: nginx
        image: nginx
