apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeName: juns-desktop-xavier # schedule pod to specific node
  containers:  
  - name: nginx
   image: nginx
   imagePullPolicy: IfNotPresent
